version: "3.8"

networks:
  monitoring:
    driver: bridge

volumes:
  prometheus_data: {}

services:
  roaster:
    depends_on:
        - prometheus
        - zipkin
    build:
      context: .
      dockerfile: Roaster/Dockerfile
    container_name: roaster
    restart: unless-stopped
    networks:
      - monitoring
    ports:
      - 8080:80
    environment:
      # - OTLP_ENDPOINT_URL=
      - ZIPKIN_URL=http://zipkin:9411/api/v2/spans

  prometheus:
    image: prom/prometheus:v2.55.1
    container_name: prometheus
    restart: unless-stopped
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
      - prometheus_data:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/etc/prometheus/console_libraries"
      - "--web.console.templates=/etc/prometheus/consoles"
      - "--web.enable-lifecycle"
    ports:
      - 9090:9090
    networks:
      - monitoring

  zipkin:
    image: openzipkin/zipkin:3
    container_name: zipkin
    restart: unless-stopped
    ports:
      - 9411:9411    
    networks:
      - monitoring