name: Deploy to app service

on:
  workflow_dispatch:
    inputs:
      environment:
        description: "Azure Web App"
        type: environment
        required: true
      version:
        description: "Version"
        type: string
        required: true

permissions:
  contents: read

jobs:
  deploy:
    environment: "${{ github.event.inputs.environment }}"
    permissions:
      contents: none
    runs-on: ubuntu-24.04
    env:
      IMAGE: "${{ vars.ACR_URL }}/${{ vars.REPOSITORY }}:${{ github.event.inputs.version }}"
    steps:
      - name: Validate version
        run: |
          echo "Validating that tag is a production deploy tag (must be in the format [0-9]+.[0-9]+.[0-9]+, ex. 1.2.3)"
          echo "${{ github.event.inputs.version }}" | grep -P '[0-9]+.[0-9]+.[0-9]+'

      - name: Login
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.ACR_URL }}
          username: ${{ secrets.AZURE_CLIENT_ID }}
          password: ${{ secrets.AZURE_CLIENT_SECRET }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ vars.AZURE_WEBAPP_NAME }}
          publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
          images: "${{ env.IMAGE }}"
