name: Docker Image CI

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-24.04
    env:
      DOCKERFILE: "./Roaster/Dockerfile"
      CONTEXT: "."
      REF: ${{ github.head_ref || github.ref_name }}
    steps:
      - uses: actions/checkout@v4

      - name: Get current tag
        run: |
          echo "Tag name from REF: $REF"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login
        uses: docker/login-action@v3
        with:
          registry: ${{ vars.ACR_URL }}
          username: ${{ secrets.AZURE_CLIENT_ID }}
          password: ${{ secrets.AZURE_CLIENT_SECRET }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: ${{ env.CONTEXT }}
          file: ${{ env.DOCKERFILE }}
          push: true
          tags: ${{ vars.REPOSITORY }}:${{ env.REF }}
          labels: ${{ github.sha }}
          platforms: linux/amd64
