name: Docker Image CI

on:
  pull_request:
    branches: ["master"]
  push:
    tags:
      - "v*.*.*"

permissions:
  contents: read

jobs:
  docker:
    runs-on: ubuntu-24.04
    env:
      DOCKERFILE: "./Roaster/Dockerfile"
      CONTEXT: "."
      IMAGE_NAME: "roaster"
      REPOSITORY: "webapi"
    steps:
      - uses: actions/checkout@v4

      - name: GitHub Tag Name example
        run: |
          echo "Tag name from GITHUB_REF_NAME: $GITHUB_REF_NAME"
          echo "Tag name from github.ref_name: ${{ github.ref_name }}"

      # - name: Set up QEMU
      #   uses: docker/setup-qemu-action@v3

      # - name: Set up Docker Buildx
      #   uses: docker/setup-buildx-action@v3

      # - name: Login to Docker Hub
      #   uses: docker/login-action@v3
      #   with:
      #     registry: ${{ vars.ACR_URL }}
      #     username: ${{ vars.AZURE_CLIENT_ID }}
      #     password: ${{ secrets.AZURE_CLIENT_SECRET }}

      # - name: Build and push
      #   uses: docker/build-push-action@v6
      #   with:
      #     context: ${{ env.CONTEXT }}
      #     file: ${{ env.DOCKERFILE }}
      #     push: true
      #     tags: ${{ env.REPOSITORY }}/${{ env.IMAGE_NAME }}:$GITHUB_REF_NAME
      #     labels: ${{ github.sha }}
